### ISSUE TITLE
τελίτσες στο Constact

### ISSUE THREAD

**Issue by ThomasMoustas** [PavlosTzitzos/database-project#2]
Οι βουλιτσες της λίστας ονομάτων στη σελίδα contacts είναι σε λάθος θέση. Αρίστερά αντί για το κέντρο της σελίδας.

Αυτό τις κάνει να δείχνουν άσχημα, εκτός απτο ότι δεν πληρούν το σκοπό τους (να κάνουν ευδιάκριτα τα ονόματα).

Για αυτό θα πρέπει να μετακινηθούν στη σωστή τους θέση, στο κέντρο, δίπλα απτα γράμματα

**Comment by PavlosTzitzos** [comment]
Done
