### ISSUE TITLE
Δυναμικό παράθυρο 

### ISSUE THREAD

**Issue by ThomasMoustas** [PavlosTzitzos/database-project#4]
Στη σελίδα που εμφανίζεται στους χρήστες αφού συνδεθούν:

θα πρέπει να εμφανίζεται στη μέση ένα παράθυρο μορφής πίνακα που εμφανίζει τις συσχετίσεις του χρήστη με τους άλλους χρήστες.

Τα δεδομένα του πίνακα αυτού θα προέρχονται από queries στη βάση δεδομένων (mysql)

**Comment by PavlosTzitzos** [comment]
Done
